name: Newman API Tests
on: push
jobs:
  unicorn-brain-api:
    name: 'Run tests'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install Newman
        run: npm install -g newman
      - name: Install Newman Reporter
        run: npm install -g newman-reporter-htmlextra

      - name: Run Collection with OAuth2.0
        env:
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: |
          newman run unicorn-brain-2.0.postman_collection.json \
          -e non-prod.postman_environment.json \
          --env-var "client_secret=$CLIENT_SECRET" \
          --reporters json --reporter-json-export result.json  

      - name: Create Status Check based on Postman Results
        id: process-postman
        uses: lendly-telus-com/pm-result@master
        with:
          github-token: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}
          results-file: result.json
          report-name: 'Postman ${{ github.run_number }}'
          create-status-check: true
          create-pr-comment: true
          update-comment-if-one-exists: false
          ignore-test-failures: true
          timezone: 'america/denver'

      - name: Fail on Test Failures
        if: steps.process-postman.outcome == 'failure'
        run: |
          echo "There were Postman test failures."
          exit 1
